version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  kafka-setup:
    image: 'bitnami/kafka:latest'
    depends_on:
      - kafka
    command: >
      bash -c "
        echo Waiting for Kafka to be ready... &&
        sleep 30 &&
        kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic topic1 &&
        kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic topic2 &&
        kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic topic3
      "

  kafdrop:
    image: 'obsidiandynamics/kafdrop'
    ports:
      - '9008:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka